"""
AERMINUTE control file generation and execution.

AERMINUTE processes 1-minute ASOS wind data to supplement the
standard hourly observations used by AERMET. Only applicable for
US ASOS stations.
"""

import os
import subprocess

_BIN_DIR = os.path.join(os.path.dirname(__file__), '..', 'bin')


def _aerminute_exe():
    exe = os.path.join(_BIN_DIR, 'aerminute.exe')
    if os.path.exists(exe):
        return exe
    exe2 = os.path.join(_BIN_DIR, 'aerminute')
    if os.path.exists(exe2):
        return exe2
    return None


def generate_control_file(work_dir, year, wban, onemin_files,
                           surface_file=None):
    """
    Generate AERMINUTE control file.

    Args:
        work_dir: Working directory
        year: Data year
        wban: 5-digit WBAN station ID
        onemin_files: List of 1-minute ASOS data file paths
        surface_file: Path to surface (ISD) file for comparison

    Returns path to control file.
    """
    ctrl_path = os.path.join(work_dir, f'aerminute_{year}.inp')
    output_path = os.path.join(work_dir, f'aerminute_{year}.out')
    summary_path = os.path.join(work_dir, f'aerminute_{year}_summary.out')
    comp_path = os.path.join(work_dir, f'aerminute_{year}_comp.out')

    # Build file list
    file_lines = []
    for fpath in onemin_files:
        file_lines.append(f'   DATAFILE   {fpath}')
    files_section = '\n'.join(file_lines)

    # Surface file line (optional)
    surf_line = ''
    if surface_file:
        surf_line = f'   SURFDATA   {surface_file}'

    ctrl = f"""** AERMINUTE Control File
** Generated by AERMET Automation Tool

   STARTEND  {year}0101  {year}1231
   WESSION   {wban}
{files_section}
{surf_line}
   OUTFILE   {output_path}
   SUMMARY   {summary_path}
   COMPFILE  {comp_path}
"""

    with open(ctrl_path, 'w') as f:
        f.write(ctrl)
    return ctrl_path


def run_aerminute(ctrl_path, work_dir, year, progress_cb=None):
    """Execute AERMINUTE with a control file."""
    exe = _aerminute_exe()
    if not exe:
        return {
            'success': False,
            'error': 'AERMINUTE executable not found. Place aerminute.exe in aermet/bin/',
        }

    if progress_cb:
        progress_cb('running', f'Running AERMINUTE for {year}...')

    try:
        ctrl_filename = os.path.basename(ctrl_path)
        result = subprocess.run(
            [exe],
            input=ctrl_filename + '\n',
            capture_output=True,
            text=True,
            cwd=work_dir,
            timeout=300,
        )

        output_path = os.path.join(work_dir, f'aerminute_{year}.out')
        success = result.returncode == 0 and os.path.exists(output_path)

        if progress_cb:
            progress_cb('done' if success else 'error',
                        f'AERMINUTE {year} complete' if success else f'AERMINUTE {year} failed')

        return {
            'success': success,
            'return_code': result.returncode,
            'output_path': output_path if success else None,
            'stdout': result.stdout,
            'stderr': result.stderr,
        }
    except FileNotFoundError:
        return {'success': False, 'error': 'AERMINUTE executable not found'}
    except subprocess.TimeoutExpired:
        return {'success': False, 'error': 'AERMINUTE timed out'}


def check_aerminute_availability(wban, start_year, end_year):
    """
    Check if 1-minute ASOS data is likely available for a station.
    AERMINUTE data is generally available for ASOS stations from ~2000 onward.
    """
    if not wban or wban == '99999':
        return False
    # 1-minute data is generally available from 2000 onward for ASOS stations
    if end_year < 2000:
        return False
    return True
