"""
AERSURFACE control file generation and execution.

AERSURFACE computes surface characteristics (albedo, Bowen ratio,
surface roughness) from NLCD land-use data for use in AERMET Stage 3.
Only applicable for US sites with NLCD data available.
"""

import os
import subprocess

_BIN_DIR = os.path.join(os.path.dirname(__file__), '..', 'bin')


def _aersurface_exe():
    exe = os.path.join(_BIN_DIR, 'aersurface.exe')
    if os.path.exists(exe):
        return exe
    exe2 = os.path.join(_BIN_DIR, 'aersurface')
    if os.path.exists(exe2):
        return exe2
    return None


def generate_control_file(work_dir, nlcd_path, center_lat, center_lon,
                           is_airport=True, temporal='MONTHLY',
                           num_sectors=12, anemometer_height=10.0):
    """
    Generate AERSURFACE control file.

    Args:
        work_dir: Working directory for output files
        nlcd_path: Path to NLCD GeoTIFF file
        center_lat, center_lon: Station coordinates (refined by user)
        is_airport: Whether station is at an airport (affects processing)
        temporal: 'MONTHLY' or 'SEASONAL'
        num_sectors: Number of wind direction sectors (default 12)
        anemometer_height: NWS anemometer height in meters

    Returns path to control file.
    """
    ctrl_path = os.path.join(work_dir, 'aersurface.inp')
    output_path = os.path.join(work_dir, 'aersurface.out')

    airport_flag = 'AIRPORT' if is_airport else 'NOAIRPORT'

    # Build sector definitions
    sector_size = 360.0 / num_sectors
    sector_lines = []
    for i in range(num_sectors):
        start_angle = i * sector_size
        end_angle = (i + 1) * sector_size
        sector_lines.append(f'   SECTOR   {i + 1}   {start_angle:.0f}   {end_angle:.0f}')

    sectors = '\n'.join(sector_lines)

    ctrl = f"""** AERSURFACE Control File
** Generated by AERMET Automation Tool

CO STARTING
   TITLEONE  AERSURFACE Analysis
   OPTIONS   {airport_flag}
   ZOTEFG    {temporal}
   CENTERLL  {center_lat:.6f}  {center_lon:.6f}
   NLCDGRID  {nlcd_path}
   AESSION   {output_path}
{sectors}
CO FINISHED

OU STARTING
   SFCCHAR   {output_path}
OU FINISHED
"""

    with open(ctrl_path, 'w') as f:
        f.write(ctrl)
    return ctrl_path


def run_aersurface(ctrl_path, work_dir, progress_cb=None):
    """Execute AERSURFACE with a control file."""
    exe = _aersurface_exe()
    if not exe:
        return {
            'success': False,
            'error': 'AERSURFACE executable not found. Place aersurface.exe in aermet/bin/',
        }

    if progress_cb:
        progress_cb('running', 'Running AERSURFACE...')

    try:
        result = subprocess.run(
            [exe],
            input='aersurface.inp\n',
            capture_output=True,
            text=True,
            cwd=work_dir,
            timeout=300,
        )

        output_path = os.path.join(work_dir, 'aersurface.out')
        success = result.returncode == 0 and os.path.exists(output_path)

        if progress_cb:
            progress_cb('done' if success else 'error',
                        'AERSURFACE complete' if success else 'AERSURFACE failed')

        return {
            'success': success,
            'return_code': result.returncode,
            'output_path': output_path if success else None,
            'stdout': result.stdout,
            'stderr': result.stderr,
        }
    except FileNotFoundError:
        return {'success': False, 'error': 'AERSURFACE executable not found'}
    except subprocess.TimeoutExpired:
        return {'success': False, 'error': 'AERSURFACE timed out'}


# Reference values for manual entry (non-US sites)
LAND_USE_REFERENCE = {
    'urban': {'albedo': 0.18, 'bowen': 1.5, 'roughness': 1.0},
    'suburban': {'albedo': 0.18, 'bowen': 1.0, 'roughness': 0.5},
    'cultivated': {'albedo': 0.20, 'bowen': 1.0, 'roughness': 0.1},
    'grassland': {'albedo': 0.20, 'bowen': 1.0, 'roughness': 0.05},
    'forest_deciduous': {'albedo': 0.18, 'bowen': 0.6, 'roughness': 1.0},
    'forest_coniferous': {'albedo': 0.12, 'bowen': 0.6, 'roughness': 1.3},
    'water': {'albedo': 0.10, 'bowen': 0.0, 'roughness': 0.001},
    'desert': {'albedo': 0.30, 'bowen': 4.0, 'roughness': 0.05},
    'wetland': {'albedo': 0.14, 'bowen': 0.2, 'roughness': 0.2},
    'snow_ice': {'albedo': 0.60, 'bowen': 0.5, 'roughness': 0.005},
}
