#![allow(dead_code)]
/// AERMINUTE control file generation and execution.
use serde::Serialize;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

fn aerminute_exe() -> Option<PathBuf> {
    let exe_dir = std::env::current_exe()
        .ok()
        .and_then(|p| p.parent().map(|p| p.to_path_buf()))
        .unwrap_or_else(|| PathBuf::from("."));
    let exe = exe_dir.join("bin").join("aerminute.exe");
    if exe.exists() {
        return Some(exe);
    }
    let exe2 = exe_dir.join("bin").join("aerminute");
    if exe2.exists() {
        return Some(exe2);
    }
    None
}

pub fn generate_control_file(
    work_dir: &Path,
    year: i32,
    wban: &str,
    onemin_files: &[String],
    surface_file: Option<&str>,
) -> Result<PathBuf, String> {
    let ctrl_path = work_dir.join(format!("aerminute_{year}.inp"));
    let output_path = work_dir.join(format!("aerminute_{year}.out"));
    let summary_path = work_dir.join(format!("aerminute_{year}_summary.out"));
    let comp_path = work_dir.join(format!("aerminute_{year}_comp.out"));

    let file_lines: Vec<String> = onemin_files
        .iter()
        .map(|f| format!("   DATAFILE   {f}"))
        .collect();

    let surf_line = surface_file
        .map(|f| format!("   SURFDATA   {f}"))
        .unwrap_or_default();

    let ctrl = format!(
        "** AERMINUTE Control File\n\
         ** Generated by AERMET Automation Tool\n\
         \n\
         \x20  STARTEND  {year}0101  {year}1231\n\
         \x20  WESSION   {wban}\n\
         {}\n\
         {surf_line}\n\
         \x20  OUTFILE   {}\n\
         \x20  SUMMARY   {}\n\
         \x20  COMPFILE  {}\n",
        file_lines.join("\n"),
        output_path.to_string_lossy(),
        summary_path.to_string_lossy(),
        comp_path.to_string_lossy(),
    );

    fs::write(&ctrl_path, ctrl).map_err(|e| format!("Write: {e}"))?;
    Ok(ctrl_path)
}

#[derive(Debug, Clone, Serialize)]
pub struct AerminuteResult {
    pub success: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub return_code: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub output_path: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}

pub fn run_aerminute(ctrl_path: &Path, work_dir: &Path, year: i32) -> AerminuteResult {
    let exe = match aerminute_exe() {
        Some(e) => e,
        None => {
            return AerminuteResult {
                success: false,
                return_code: None,
                output_path: None,
                error: Some("AERMINUTE executable not found".to_string()),
            }
        }
    };

    let ctrl_filename = ctrl_path
        .file_name()
        .unwrap_or_default()
        .to_string_lossy()
        .to_string();

    let result = Command::new(&exe)
        .stdin(std::process::Stdio::piped())
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped())
        .current_dir(work_dir)
        .spawn()
        .and_then(|mut child| {
            use std::io::Write;
            if let Some(ref mut stdin) = child.stdin {
                let _ = write!(stdin, "{ctrl_filename}\n");
            }
            child.wait_with_output()
        });

    match result {
        Ok(output) => {
            let output_file = work_dir.join(format!("aerminute_{year}.out"));
            let success = output.status.success() && output_file.exists();
            AerminuteResult {
                success,
                return_code: Some(output.status.code().unwrap_or(-1)),
                output_path: if success {
                    Some(output_file.to_string_lossy().to_string())
                } else {
                    None
                },
                error: None,
            }
        }
        Err(e) => AerminuteResult {
            success: false,
            return_code: None,
            output_path: None,
            error: Some(format!("Failed to run AERMINUTE: {e}")),
        },
    }
}

/// Check if 1-minute ASOS data is likely available for a station.
pub fn check_aerminute_availability(wban: &str, _start_year: i32, end_year: i32) -> bool {
    if wban.is_empty() || wban == "99999" {
        return false;
    }
    // 1-minute data generally available from 2000 onward
    end_year >= 2000
}
