/// AERSURFACE control file generation and execution.
use serde::Serialize;
use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

fn aersurface_exe() -> Option<PathBuf> {
    let exe_dir = std::env::current_exe()
        .ok()
        .and_then(|p| p.parent().map(|p| p.to_path_buf()))
        .unwrap_or_else(|| PathBuf::from("."));
    let exe = exe_dir.join("bin").join("aersurface.exe");
    if exe.exists() {
        return Some(exe);
    }
    let exe2 = exe_dir.join("bin").join("aersurface");
    if exe2.exists() {
        return Some(exe2);
    }
    None
}

#[derive(Debug, Clone, Serialize)]
pub struct LandUseRef {
    pub albedo: f64,
    pub bowen: f64,
    pub roughness: f64,
}

pub fn land_use_reference() -> HashMap<String, LandUseRef> {
    let mut m = HashMap::new();
    m.insert("urban".to_string(), LandUseRef { albedo: 0.18, bowen: 1.5, roughness: 1.0 });
    m.insert("suburban".to_string(), LandUseRef { albedo: 0.18, bowen: 1.0, roughness: 0.5 });
    m.insert("cultivated".to_string(), LandUseRef { albedo: 0.20, bowen: 1.0, roughness: 0.1 });
    m.insert("grassland".to_string(), LandUseRef { albedo: 0.20, bowen: 1.0, roughness: 0.05 });
    m.insert("forest_deciduous".to_string(), LandUseRef { albedo: 0.18, bowen: 0.6, roughness: 1.0 });
    m.insert("forest_coniferous".to_string(), LandUseRef { albedo: 0.12, bowen: 0.6, roughness: 1.3 });
    m.insert("water".to_string(), LandUseRef { albedo: 0.10, bowen: 0.0, roughness: 0.001 });
    m.insert("desert".to_string(), LandUseRef { albedo: 0.30, bowen: 4.0, roughness: 0.05 });
    m.insert("wetland".to_string(), LandUseRef { albedo: 0.14, bowen: 0.2, roughness: 0.2 });
    m.insert("snow_ice".to_string(), LandUseRef { albedo: 0.60, bowen: 0.5, roughness: 0.005 });
    m
}

pub fn generate_control_file(
    work_dir: &Path,
    nlcd_path: &str,
    center_lat: f64,
    center_lon: f64,
    is_airport: bool,
) -> Result<PathBuf, String> {
    let ctrl_path = work_dir.join("aersurface.inp");
    let output_path = work_dir.join("aersurface.out");
    let airport_flag = if is_airport { "AIRPORT" } else { "NOAIRPORT" };

    let mut sector_lines = Vec::new();
    let num_sectors = 12;
    let sector_size = 360.0 / num_sectors as f64;
    for i in 0..num_sectors {
        let start_angle = i as f64 * sector_size;
        let end_angle = (i + 1) as f64 * sector_size;
        sector_lines.push(format!("   SECTOR   {}   {start_angle:.0}   {end_angle:.0}", i + 1));
    }

    let ctrl = format!(
        "** AERSURFACE Control File\n\
         ** Generated by AERMET Automation Tool\n\
         \n\
         CO STARTING\n\
         \x20  TITLEONE  AERSURFACE Analysis\n\
         \x20  OPTIONS   {airport_flag}\n\
         \x20  ZOTEFG    MONTHLY\n\
         \x20  CENTERLL  {center_lat:.6}  {center_lon:.6}\n\
         \x20  NLCDGRID  {nlcd_path}\n\
         \x20  AESSION   {}\n\
         {}\n\
         CO FINISHED\n\
         \n\
         OU STARTING\n\
         \x20  SFCCHAR   {}\n\
         OU FINISHED\n",
        output_path.to_string_lossy(),
        sector_lines.join("\n"),
        output_path.to_string_lossy(),
    );

    fs::write(&ctrl_path, ctrl).map_err(|e| format!("Write: {e}"))?;
    Ok(ctrl_path)
}

#[derive(Debug, Clone, Serialize)]
pub struct AersurfaceResult {
    pub success: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub return_code: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub output_path: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub stdout: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub stderr: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}

pub fn run_aersurface(_ctrl_path: &Path, work_dir: &Path) -> AersurfaceResult {
    let exe = match aersurface_exe() {
        Some(e) => e,
        None => {
            return AersurfaceResult {
                success: false,
                return_code: None,
                output_path: None,
                stdout: None,
                stderr: None,
                error: Some("AERSURFACE executable not found".to_string()),
            }
        }
    };

    let result = Command::new(&exe)
        .stdin(std::process::Stdio::piped())
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped())
        .current_dir(work_dir)
        .spawn()
        .and_then(|mut child| {
            use std::io::Write;
            if let Some(ref mut stdin) = child.stdin {
                let _ = write!(stdin, "aersurface.inp\n");
            }
            child.wait_with_output()
        });

    match result {
        Ok(output) => {
            let output_file = work_dir.join("aersurface.out");
            let success = output.status.success() && output_file.exists();
            AersurfaceResult {
                success,
                return_code: Some(output.status.code().unwrap_or(-1)),
                output_path: if success {
                    Some(output_file.to_string_lossy().to_string())
                } else {
                    None
                },
                stdout: Some(String::from_utf8_lossy(&output.stdout).to_string()),
                stderr: Some(String::from_utf8_lossy(&output.stderr).to_string()),
                error: None,
            }
        }
        Err(e) => AersurfaceResult {
            success: false,
            return_code: None,
            output_path: None,
            stdout: None,
            stderr: None,
            error: Some(format!("Failed to run AERSURFACE: {e}")),
        },
    }
}
